// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Captured = sequelize.define('captured', {
    level: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    gender: {
      type: DataTypes.ENUM(
        'Female',
        'Male',
        'Unsexed',
      ),
      defaultValue: Sequelize.literal('\'Unsexed\'::"Gender"'),
      allowNull: false,
    },
  }, {
    tableName: 'Captured',
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Captured.associate = (models) => {
    Captured.belongsTo(models.pokemon, {
      foreignKey: {
        name: 'pokemonIdKey',
        field: 'pokemonId',
      },
      as: 'pokemon',
    });
    Captured.belongsTo(models.trainer, {
      foreignKey: {
        name: 'trainerIdKey',
        field: 'trainerId',
      },
      as: 'trainer',
    });
  };

  return Captured;
};
