// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Trainer = sequelize.define('trainer', {
    name: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    gender: {
      type: DataTypes.ENUM(
        'Female',
        'Male',
        'Unsexed',
      ),
    },
    age: {
      type: DataTypes.INTEGER,
    },
  }, {
    tableName: 'Trainer',
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Trainer.associate = (models) => {
    Trainer.hasMany(models.captured, {
      foreignKey: {
        name: 'trainerIdKey',
        field: 'trainerId',
      },
      as: 'trainerCaptureds',
    });
  };

  return Trainer;
};
