import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pokemon Database</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/528/528101.png" />
        
      </Head>

      <main className={styles.background}>
        <div className={styles.main}>
          <h1 className={styles.title}>
            Welcome to the Pokemon Database
          </h1>

          <p className={styles.description}>
            Can you catch them all?
          </p>

          <div className={styles.grid}>
            <Link href="/all_pokemon">
              <a className={styles.card}>
                <h2>All Pokemon &rarr;</h2>
                <p>Find in-depth information about all known Pokemon</p>
              </a>
            </Link>

            <Link href="/legendary_pokemon">
              <a className={styles.card}>
                <h2>Legendary Pokemon &rarr;</h2>
                <p>Learn about rarest and most powerful Pokemon of them all!</p>
              </a>
            </Link>

            <Link href="/abilities">
              <a className={styles.card}>
                <h2>Abilities &rarr;</h2>
                <p>Discover all the abilities Pokemon use!</p>
              </a>
            </Link>

            <Link href="/types">
              <a className={styles.card}>
                <h2>Types &rarr;</h2>
                <p>
                  Learn more about the different types of Pokemon
                </p>
              </a>
            </Link>

          </div>
        </div> 
      </main> 

     <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
