// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Generation = sequelize.define('generation', {
    generation: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
  }, {
    tableName: 'Generation',
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Generation.associate = (models) => {
    Generation.hasMany(models.pokemon, {
      foreignKey: {
        name: 'generationIdKey',
        field: 'generationId',
      },
      as: 'generationPokemon',
    });
  };

  return Generation;
};
